version: "3"
services:
  mymongodb:
    container_name: mongo_service
    image: 'mongo:7'
    ports:
      - 27017
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    image: ashkt/pennypilot-backend
    ports:
      - "8082:8082"
    depends_on:
      - mymongodb
    # env_file:
    #   - ./backend/.env
    # volumes:
    #   - ./backend:/backend
    #   - /backend/node_modules
    # networks:
    #   - finance
  frontend:
    build:
      dockerfile: dockerfile
      context: ./frontend/
    container_name: frontend
    restart: always
    image: ashkt/pennypilot-frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    # networks:
    #   - finance
    depends_on:
      - backend
# networks:
#   finance:
#     driver: bridge