version: '3'
services:
  mongo:
    container_name: mongo_service
    restart: always
    image: mongo:7
    ports:
      - '27017:27017'
    # environment:
    #    MONGO_INITDB_ROOT_USERNAME: ash 
    #    MONGO_INITDB_ROOT_PASSWORD: 123  
    #    MONGO_INITDB_DATABASE: db
  backend:
    build: backend
      # dockerfile: dockerfile
      # context: ./backend/
    container_name: backend
    restart: always
    image: ashkt/pennypilot-backend
    ports:
      - '8082:8082'
    depends_on:
      - mongo
    # env_file:
    #   - ./backend/.env
    # volumes:
    #   - ./backend:/backend
    #   - /backend/node_modules
    networks:
      - finance
  frontend:
    build: frontend
      # dockerfile: dockerfile
      # context: ./frontend/
    container_name: frontend
    restart: always
    image: ashkt/pennypilot-frontend
    ports:
      - '3000:3000'
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    networks:
      - finance
    depends_on:
      - backend
networks:
  finance:
    driver: bridge