version: '3'
services:
  backend:
    build: backend
    container_name: backend
    restart: always
    image: ashkt/pennypilot-backend
    ports:
      - '8082:8082'
    depends_on:
      - mongo
    volumes:
      - ./backend/logs.log:/backend/logs.log
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - finance
  mongo:
    container_name: mongo_service
    restart: always
    image: mongo:7
    ports:
      - '27017:27017'
    networks:
      - finance
  frontend:
    build: frontend
    container_name: frontend
    restart: always
    image: ashkt/pennypilot-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - finance
    depends_on:
      - backend
networks:
  finance:
    driver: bridge
