---
- name: Deploying Project.
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Build and start containers
      command: "/opt/homebrew/bin/docker-compose -f /Users/aakashkhot/Documents/IIITB_Sem7/PennyPilot/docker-compose.yml up -d"