# Use the base image with Node.js installed
FROM node:18

# Set the working directory to /frontend
WORKDIR /backend

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

RUN npm install

# Copy the rest of the backend code to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 8082

# Start the backend server
CMD ["node", "server.js"]
# CMD ["npm", "run","dev"]